# Log level verbosity.
log_level = "info"
# Shared volume between all microservices.
shared_volume = "/samples"
# The data source name (DSN) for connecting to the broker server (NSQD)
nsqd = "nsqd:4150"
# Topic name used by the orchestrator service to consume messages.
orchestrator_topic = "topic-filescan"
# Topic name used by the post processor service to consume messages.
postprocessor_topic = "topic-postprocessor"
# Topic name used by the meta service to consume messages.
meta_topic = "topic-meta"
# Topic name used by the pe service to consume messages.
pe_topic = "topic-pe"